# Generated by Django 6.0 on 2025-12-23 01:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('body', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaxSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_wage', models.PositiveIntegerField()),
                ('min_wage', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RoleSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=30, unique=True)),
                ('base_wage', models.PositiveIntegerField(help_text='기본 급여')),
                ('wage_type', models.CharField(choices=[('hourly', '시급'), ('monthly', '월급')], default='hourly', max_length=10)),
                ('increase_per_6_month', models.PositiveIntegerField(default=0, help_text='6개월당 인상액')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('days', models.CharField(choices=[('weekday_open', '평일 오픈'), ('weekday_close', '평일 마감'), ('weekend_open', '주말 오픈'), ('weekend_middle', '주말 미들'), ('weekend_close', '주말 마감')], max_length=20)),
                ('time_range', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='employees/')),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^010\\d{8}$', '전화번호는 010으로 시작하는 11자리여야 합니다.')])),
                ('birth_year', models.PositiveIntegerField(help_text='출생년도', validators=[django.core.validators.MinValueValidator(1955), django.core.validators.MaxValueValidator(2011)])),
                ('favorite_color', models.CharField(default='#2563eb', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}){1,2}$', '유효한 HEX 색상이어야 합니다.')])),
                ('address', models.CharField(max_length=200)),
                ('attendance_pin', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$', '출석 번호는 4자리 숫자여야 합니다.')])),
                ('role', models.CharField(choices=[('part_time', '파트타임'), ('manager', '매니저'), ('substitute', '대체근무')], default='part_time', max_length=20)),
                ('wage', models.PositiveIntegerField(default=0)),
                ('memo', models.TextField(blank=True)),
                ('color_tag', models.CharField(default='#22c55e', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}){1,2}$', '유효한 HEX 색상이어야 합니다.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.department')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.shift')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('color', models.CharField(choices=[('red', 'red'), ('blue', 'blue'), ('green', 'green'), ('purple', 'purple'), ('yellow', 'yellow')], default='blue', max_length=10)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='HiringSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', '구인중'), ('filled', '구인완료')], default='open', max_length=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.department')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.shift')),
            ],
        ),
    ]
