# Generated by Django 6.0 on 2025-12-23 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='wage_type',
            field=models.CharField(choices=[('hourly', '시급'), ('monthly', '월급')], default='hourly', max_length=10),
        ),
    ]
