# Generated by Django 6.0 on 2026-02-04 16:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_wage_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.RemoveField(
            model_name='hiringslot',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='event',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='hiringslot',
            name='shift',
        ),
        migrations.DeleteModel(
            name='MaxSetting',
        ),
        migrations.DeleteModel(
            name='RoleSetting',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='birth_year',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='favorite_color',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='image',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='memo',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='wage',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='wage_type',
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='resign_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='attendance_pin',
            field=models.CharField(max_length=4, unique=True, validators=[django.core.validators.RegexValidator('^\\d{4}$', '출석 번호는 4자리 숫자여야 합니다.')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='HiringSlot',
        ),
        migrations.DeleteModel(
            name='Shift',
        ),
    ]
