# Generated by Django 6.0 on 2026-02-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_delete_announcement_remove_hiringslot_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_breaktime',
            field=models.BooleanField(default=True),
        ),
    ]
