# Generated by Django 6.0 on 2026-02-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_is_breaktime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='is_breaktime',
            field=models.BooleanField(default=False),
        ),
    ]
