# Generated by Django 6.0 on 2026-02-21 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employee_is_breaktime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_breaktime',
        ),
    ]
