# Generated by Django 6.0 on 2026-02-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('planned', '근무 예정'), ('working', '근무중'), ('finished', '퇴근'), ('absent', '결근')], default='working', max_length=20),
        ),
    ]
