# Generated by Django 6.0 on 2026-02-04 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='memo',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='status',
        ),
    ]
