# Generated by Django 6.0 on 2026-02-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0002_attendancerecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='breaktime',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
