# Generated by Django 6.0 on 2026-02-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0003_attendancerecord_breaktime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='breaktime',
            field=models.IntegerField(default=0),
        ),
    ]
