# Generated by Django 6.0 on 2026-02-21 19:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_wage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('effective_start_date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wages', to='employees.employee')),
            ],
            options={
                'ordering': ['-effective_start_date'],
            },
        ),
    ]
