# Generated by Django 5.2.7 on 2025-12-23 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='이메일 알림')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='푸시 알림')),
                ('language', models.CharField(default='ko', max_length=10, verbose_name='언어')),
                ('theme', models.CharField(choices=[('light', '라이트'), ('dark', '다크')], default='light', max_length=10, verbose_name='테마')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
