# Generated by Django 6.0 on 2026-02-21 19:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('attendance_pin', models.CharField(max_length=4, unique=True, validators=[django.core.validators.RegexValidator('^\\d{4}$', '출석 번호는 4자리 숫자여야 합니다.')])),
                ('color_tag', models.CharField(default='#22c55e', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}){1,2}$', '유효한 HEX 색상이어야 합니다.')])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(blank=True, null=True)),
                ('resign_at', models.DateField(blank=True, null=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='hr_project.store')),
            ],
        ),
    ]
