# Generated by Django 6.0 on 2026-02-21 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.IntegerField(choices=[(0, '오픈'), (1, '미들'), (2, '마감')])),
                ('work_day', models.IntegerField(choices=[(0, '월'), (1, '화'), (2, '수'), (3, '목'), (4, '금'), (5, '토'), (6, '일')])),
                ('work_time', models.IntegerField(choices=[(0, '8:00 - 10:00'), (1, '8:00 - 14:00'), (2, '11:00 - 15:00'), (3, '18:00 - 22:00'), (4, '8:30 - 14:30'), (5, '10:00 - 16:00'), (6, '14:00 - 20:00'), (7, '16:00 - 22:00')])),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='DayWorkPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('planned_start', models.TimeField(blank=True, null=True)),
                ('planned_end', models.TimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dayworkplans', to='employees.employee')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='day_work_plans', to='schedules.schedule')),
            ],
        ),
    ]
