# Generated by Django 6.0 on 2026-02-27 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='work_time',
        ),
    ]
